### ISSUE TITLE
Not working in Blender 4.5

### ISSUE THREAD

**Issue by jeremielim** [CGCookie/retopoflow#1577]
I just updated to blender 4.5 and the plug-in disappeared from edit and add menus. I tried uninstalling and reinstalling but it can't run at all. screenshots attached

<img width="96" height="62" alt="Image" src="https://github.com/user-attachments/assets/349ba191-49e2-48b0-8d3d-fba8255d4468" />
<img width="1012" height="720" alt="Image" src="https://github.com/user-attachments/assets/a8bb298c-8fb9-44b0-b4ea-2d4bc11de027" />

**Comment by vxlcoder** [comment]
Thanks for the report, @jeremielim.

Could you see if anything is reported in the terminal?  Below is a link to directions for running Blender from the terminal, which might shine some light on the bug so we can get it fixed!

https://docs.retopoflow.com/v4/debugging.html#osx

**Comment by jeremielim** [comment]
@vxlcoder tried to uninstall and reinstall again and this is the output in the terminal

```
DROP FILE: /Users/jeremie/Downloads/Retopoflow_v4.0.0_beta_03 (1).zip
Addon Common: use_bgl_default=False use_gpu_default=True use_gpu_scissor=True
ERROR (gpu.shader): pyGPU_Shader Fragment Shader: 
      | 
  166 | float gl_FragDepth;
      |       ^
      | GPU_shader_shared_utils.hh:149:7: Error: duplicate member 'gl_FragDepth'
      | 
      | source/blender/gpu/metal/mtl_shader_generator.mm:1795:7: Note: previous declaration is here
      | 
      | float gl_FragDepth;
      |       ^

Caught Exception Shader Compile Error, see console for more details while trying to create shader
const float TAU = 6.28318530718;
const bool srgbTarget = true;
float radius()      { return options.settings[0]; }
float width()       { return options.settings[1]; }
float depth_near()  { return options.settings[2]; }
float depth_far()   { return options.settings[3]; }
void main() {
    float ang = TAU * pos.x;
    float r   = radius();
    float rio = r + (pos.y - 0.5) * (width() + 0.000001);
    vec3  c   = options.center.xyz;
    vec3  v   = options.plane_x.xyz * cos(ang) + options.plane_y.xyz * sin(ang);
    vec4  pp  = options.MVPMatrix * vec4(c + v * rio,  1.0);
    vec4  pcp = options.MVPMatrix * vec4(c + v * r,    1.0);
    gl_Position = pp;
    vpos = pp.xy  * options.screensize.xy;
    cpos = pcp.xy * options.screensize.xy;
}
const float TAU = 6.28318530718;
const bool srgbTarget = true;
float radius()      { return options.settings[0]; }
float width()       { return options.settings[1]; }
float depth_near()  { return options.settings[2]; }
float depth_far()   { return options.settings[3]; }
vec4 blender_srgb_to_framebuffer_space(vec4 in_color)
{
    if (srgbTarget) {
        vec3 c = max(in_color.rgb, vec3(0.0));
        vec3 c1 = c * (1.0 / 12.92);
        vec3 c2 = pow((c + 0.055) * (1.0 / 1.055), vec3(2.4));
        in_color.rgb = mix(c1, c2, step(vec3(0.04045), c));
    }
    return in_color;
}
void main() {
    float alpha = 1.0;
    outColor = blender_srgb_to_framebuffer_space(options.color * vec4(1.0,1.0,1.0,alpha));
    gl_FragDepth = mix(depth_far(), depth_near(), gl_FragCoord.z);
}
ERROR WHILE COMPILING SHADER circle_3D.glsl
Error: 
```

**Comment by vxlcoder** [comment]
oh, interesting!  i wonder if this is an OSX (metal) + Blender 4.5 thing.  (i'm running Blender 4.5 on Linux, and I don't see this issue)

@jlampel do you have access to an OSX machine to test this?

**Comment by jlampel** [comment]
Tested on an M4 Mac and I am indeed getting an error in Blender 4.5. Here it is with slightly more info at the end:

```
Addon Common: use_bgl_default=False use_gpu_default=True use_gpu_scissor=True
ERROR (gpu.shader): pyGPU_Shader Fragment Shader: 
      | 
  166 | float gl_FragDepth;
      |       ^
      | GPU_shader_shared_utils.hh:149:7: Error: duplicate member 'gl_FragDepth'
      | 
      | source/blender/gpu/metal/mtl_shader_generator.mm:1795:7: Note: previous declaration is here
      | 
      | float gl_FragDepth;
      |       ^

Caught Exception Shader Compile Error, see console for more details while trying to create shader
const float TAU = 6.28318530718;
const bool srgbTarget = true;
float radius()      { return options.settings[0]; }
float width()       { return options.settings[1]; }
float depth_near()  { return options.settings[2]; }
float depth_far()   { return options.settings[3]; }
void main() {
    float ang = TAU * pos.x;
    float r   = radius();
    float rio = r + (pos.y - 0.5) * (width() + 0.000001);
    vec3  c   = options.center.xyz;
    vec3  v   = options.plane_x.xyz * cos(ang) + options.plane_y.xyz * sin(ang);
    vec4  pp  = options.MVPMatrix * vec4(c + v * rio,  1.0);
    vec4  pcp = options.MVPMatrix * vec4(c + v * r,    1.0);
    gl_Position = pp;
    vpos = pp.xy  * options.screensize.xy;
    cpos = pcp.xy * options.screensize.xy;
}
const float TAU = 6.28318530718;
const bool srgbTarget = true;
float radius()      { return options.settings[0]; }
float width()       { return options.settings[1]; }
float depth_near()  { return options.settings[2]; }
float depth_far()   { return options.settings[3]; }
vec4 blender_srgb_to_framebuffer_space(vec4 in_color)
{
    if (srgbTarget) {
        vec3 c = max(in_color.rgb, vec3(0.0));
        vec3 c1 = c * (1.0 / 12.92);
        vec3 c2 = pow((c + 0.055) * (1.0 / 1.055), vec3(2.4));
        in_color.rgb = mix(c1, c2, step(vec3(0.04045), c));
    }
    return in_color;
}
void main() {
    float alpha = 1.0;
    outColor = blender_srgb_to_framebuffer_space(options.color * vec4(1.0,1.0,1.0,alpha));
    gl_FragDepth = mix(depth_far(), depth_near(), gl_FragCoord.z);
}
ERROR WHILE COMPILING SHADER circle_3D.glsl
Traceback (most recent call last):
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/drawing.py", line 542, in create_shader
    ret = gpustate.gpu_shader(f'drawing {fn_glsl}', vert_source, frag_source)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/gpustate.py", line 634, in gpu_shader
    raise e
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/gpustate.py", line 629, in gpu_shader
    shader = gpu.shader.create_from_info(shader_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Shader Compile Error, see console for more details

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender 4.5.app/Contents/Resources/4.5/scripts/modules/addon_utils.py", line 432, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/Blender 4.5.app/Contents/Resources/4.5/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/__init__.py", line 60, in <module>
    from .retopoflow.rfcore import RFCore
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/retopoflow/rfcore.py", line 29, in <module>
    from ..addon_common.common.blender import iter_all_view3d_areas, iter_all_view3d_spaces
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/__init__.py", line 59, in <module>
    from . import drawing as _
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/drawing.py", line 573, in <module>
    shader_3D_circle, ubos_3D_circle = create_shader('circle_3D.glsl')
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jonathanlampel/Library/Application Support/Blender/4.5/extensions/vscode_development/retopoflow/addon_common/common/drawing.py", line 547, in create_shader
    assert False
AssertionError
```

**Comment by vxlcoder** [comment]
I'm wondering if this is a Blender bug.

@jeremielim or @jlampel, could you try running Blender from terminal, then open a text editor, create new text, paste in the following code, run it, the copy the terminal output and paste it here?

```
import gpu
shader_info = gpu.types.GPUShaderCreateInfo()
shader_info.vertex_source('''void main() { gl_Position = vec4(1,1,1,1); }''')
shader_info.fragment_source('''void main() { gl_FragDepth = gl_FragCoord.x; }''')
shader = gpu.shader.create_from_info(shader_info)
print(shader)
```

I do not have a mac to test this on :(

**Comment by vxlcoder** [comment]
for reference, this is what is printed on my Linux laptop.

```
<GPUShader object at 0x747a68df6370>
```

**Comment by jlampel** [comment]
Here is what I get in the console on OSX:

```
ERROR (gpu.shader): pyGPU_Shader Fragment Shader: 
      | 
   32 | 
      |               ^
      | draw_colormanagement_lib.glsl:1:15: Error: use of undeclared identifier 'gl_FragDepth'

Error: Python: Traceback (most recent call last):
  File "/Text", line 5, in <module>
Exception: Shader Compile Error, see console for more details
```

**Comment by vxlcoder** [comment]
weird.  ok, try this @jlampel 

```
import gpu
shader_info = gpu.types.GPUShaderCreateInfo()
shader_info.vertex_source('''void main() { gl_Position = vec4(1,1,1,1); }''')
shader_info.fragment_source('''void main() { gl_FragDepth = gl_FragCoord.x; }''')
shader_info.depth_write('ANY')
shader = gpu.shader.create_from_info(shader_info)
print(shader)
```

**Comment by jlampel** [comment]
That runs just fine!
`<GPUShader object at 0x357d78210>`

**Comment by jlampel** [comment]
Also interesting note that 4.5 is also giving trouble to Intel mac users, not just Metal mac users. From the SH inbox:

> Hey there. I've loved retopoflow 3, used it just all the time. It's great. Can't wait to use 4. 
> 
> Currently, I'm unable to enable the beta add-on in blender 4.5 on a mac (intel). I know the setup isn't ideal -- GPU is meh -- but I'm hoping it's still possible. 
> 
> I think this line in shaders/circle_3D.glsl is the main problem:
> 
> ```
> // UNFORTUNATELY, as of 2025.03.08, there appears to be no way to assign to gl_FragDepth!
> 
>     // https://developer.blender.org/docs/handbook/guidelines/glsl/#driver-differences
> 
>     // implies that there is a way, but this is in Blender source, and this doesn't seem to be
> 
>     // exposed to bpy :(
> 
>     gl_FragDepth = mix(depth_far(), depth_near(), gl_FragCoord.z);
> ```
> 
> 
> That  fragDepth var is what's causing it to not be able to run.

**Comment by vxlcoder** [comment]
@jlampel can you try pulling ^^ to see if that fixes it for osx?

**Comment by jlampel** [comment]
That works!!

**Comment by jlampel** [comment]
No errors on my end after using every tool. Anything in particular I should test that uses that part of the GPU module?

**Comment by vxlcoder** [comment]
that _should_ be it.  we're using fewer shaders than in rf3, so contours (circle_3d) and polypen (point, triangle, lineseg, etc) should be sufficient for testing.  the issue was initially circle_3d, but if no error messages are reported to terminal i think we can call it good!

**Comment by jeremielim** [comment]
Thanks for the quick fix, I installed the latest beta and it works for me too

**Comment by davephenderson** [comment]
Hi, I have the same issue on 4.5. How do I fix it on my install? Mac OS

**Comment by jlampel** [comment]
Hey @davephenderson  if you haven't already, please upgrade to beta 5 which has a fix for the issue. If you are using beta 5 and still experience it, please let us know!
