### ISSUE TITLE
AttributeError: 'RFSource' object has no attribute 'bme'

### ISSUE THREAD

**Issue by blessedcoolant** [CGCookie/retopoflow#996]
New error with Retopo 3.1.0 and Blender 3.0 (latest daily build).

The Retopoflow UI gets stuck at loading (setting up source meshes) and never loads. Console error listed in title.

**Comment by vxlcoder** [comment]
thanks for the report. will take a look

**Comment by vxlcoder** [comment]
i was able to get RF v3.1.1 to run in today's (2021.06.09) Blender 3.0.0 alpha, but there's no guarantee that RF will continue to work in Blender 3.0 until Blender becomes more stable.

unfortunately, Blender 3.0 is still very much in alpha.  bpy and the docs are still out of sync of the blender core code, and sadly the api transitions so much during alpha stage that it because nearly impossible to keep everything working.

we will definitely take a more serious look at supporting blender 3.0 when it gets to beta, possibly sooner.

thanks!

**Comment by jlampel** [comment]
Confirmed fixed

**Comment by blessedcoolant** [comment]
I managed to get it to work by removing all references to Deform from RF. Not sure how much functionality got impacted. At the moment it seems to be working fine. But I am not sure entirely.

**Comment by vxlcoder** [comment]
the `deform` keyword was deprecated in 2.93 and removed in 3.0.  you made the same change as I did in the commit above :) so I think you should be fine.  feel free to update to the latest version (specify branch `v3.1.1`) using the updater system if you'd like to use the official version.

great work!

**Comment by blessedcoolant** [comment]
Thanks I'll update. :) And thank you for the fix
